// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpcProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InfoServiceClient is the client API for InfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InfoServiceClient interface {
	StrGame32(ctx context.Context, in *InfoEmpty, opts ...grpc.CallOption) (*AnswerInfo, error)
	StrGame64(ctx context.Context, in *InfoEmpty, opts ...grpc.CallOption) (*AnswerInfo, error)
	StrGame128(ctx context.Context, in *InfoEmpty, opts ...grpc.CallOption) (*AnswerInfo, error)
	AllUsers(ctx context.Context, in *InfoEmpty, opts ...grpc.CallOption) (*AnswerInfo, error)
	UserByID(ctx context.Context, in *InfoEmpty, opts ...grpc.CallOption) (*AnswerInfo, error)
	AddUser(ctx context.Context, in *InfoEmpty, opts ...grpc.CallOption) (*AnswerInfo, error)
	UserDelete(ctx context.Context, in *InfoEmpty, opts ...grpc.CallOption) (*AnswerInfo, error)
}

type infoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInfoServiceClient(cc grpc.ClientConnInterface) InfoServiceClient {
	return &infoServiceClient{cc}
}

func (c *infoServiceClient) StrGame32(ctx context.Context, in *InfoEmpty, opts ...grpc.CallOption) (*AnswerInfo, error) {
	out := new(AnswerInfo)
	err := c.cc.Invoke(ctx, "/go.micro.srv.grpc.InfoService/StrGame32", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoServiceClient) StrGame64(ctx context.Context, in *InfoEmpty, opts ...grpc.CallOption) (*AnswerInfo, error) {
	out := new(AnswerInfo)
	err := c.cc.Invoke(ctx, "/go.micro.srv.grpc.InfoService/StrGame64", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoServiceClient) StrGame128(ctx context.Context, in *InfoEmpty, opts ...grpc.CallOption) (*AnswerInfo, error) {
	out := new(AnswerInfo)
	err := c.cc.Invoke(ctx, "/go.micro.srv.grpc.InfoService/StrGame128", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoServiceClient) AllUsers(ctx context.Context, in *InfoEmpty, opts ...grpc.CallOption) (*AnswerInfo, error) {
	out := new(AnswerInfo)
	err := c.cc.Invoke(ctx, "/go.micro.srv.grpc.InfoService/AllUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoServiceClient) UserByID(ctx context.Context, in *InfoEmpty, opts ...grpc.CallOption) (*AnswerInfo, error) {
	out := new(AnswerInfo)
	err := c.cc.Invoke(ctx, "/go.micro.srv.grpc.InfoService/UserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoServiceClient) AddUser(ctx context.Context, in *InfoEmpty, opts ...grpc.CallOption) (*AnswerInfo, error) {
	out := new(AnswerInfo)
	err := c.cc.Invoke(ctx, "/go.micro.srv.grpc.InfoService/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoServiceClient) UserDelete(ctx context.Context, in *InfoEmpty, opts ...grpc.CallOption) (*AnswerInfo, error) {
	out := new(AnswerInfo)
	err := c.cc.Invoke(ctx, "/go.micro.srv.grpc.InfoService/UserDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfoServiceServer is the server API for InfoService service.
// All implementations must embed UnimplementedInfoServiceServer
// for forward compatibility
type InfoServiceServer interface {
	StrGame32(context.Context, *InfoEmpty) (*AnswerInfo, error)
	StrGame64(context.Context, *InfoEmpty) (*AnswerInfo, error)
	StrGame128(context.Context, *InfoEmpty) (*AnswerInfo, error)
	AllUsers(context.Context, *InfoEmpty) (*AnswerInfo, error)
	UserByID(context.Context, *InfoEmpty) (*AnswerInfo, error)
	AddUser(context.Context, *InfoEmpty) (*AnswerInfo, error)
	UserDelete(context.Context, *InfoEmpty) (*AnswerInfo, error)
	mustEmbedUnimplementedInfoServiceServer()
}

// UnimplementedInfoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInfoServiceServer struct {
}

func (UnimplementedInfoServiceServer) StrGame32(context.Context, *InfoEmpty) (*AnswerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StrGame32 not implemented")
}
func (UnimplementedInfoServiceServer) StrGame64(context.Context, *InfoEmpty) (*AnswerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StrGame64 not implemented")
}
func (UnimplementedInfoServiceServer) StrGame128(context.Context, *InfoEmpty) (*AnswerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StrGame128 not implemented")
}
func (UnimplementedInfoServiceServer) AllUsers(context.Context, *InfoEmpty) (*AnswerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllUsers not implemented")
}
func (UnimplementedInfoServiceServer) UserByID(context.Context, *InfoEmpty) (*AnswerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserByID not implemented")
}
func (UnimplementedInfoServiceServer) AddUser(context.Context, *InfoEmpty) (*AnswerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedInfoServiceServer) UserDelete(context.Context, *InfoEmpty) (*AnswerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserDelete not implemented")
}
func (UnimplementedInfoServiceServer) mustEmbedUnimplementedInfoServiceServer() {}

// UnsafeInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InfoServiceServer will
// result in compilation errors.
type UnsafeInfoServiceServer interface {
	mustEmbedUnimplementedInfoServiceServer()
}

func RegisterInfoServiceServer(s grpc.ServiceRegistrar, srv InfoServiceServer) {
	s.RegisterService(&InfoService_ServiceDesc, srv)
}

func _InfoService_StrGame32_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).StrGame32(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.grpc.InfoService/StrGame32",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).StrGame32(ctx, req.(*InfoEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InfoService_StrGame64_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).StrGame64(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.grpc.InfoService/StrGame64",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).StrGame64(ctx, req.(*InfoEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InfoService_StrGame128_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).StrGame128(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.grpc.InfoService/StrGame128",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).StrGame128(ctx, req.(*InfoEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InfoService_AllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).AllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.grpc.InfoService/AllUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).AllUsers(ctx, req.(*InfoEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InfoService_UserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).UserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.grpc.InfoService/UserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).UserByID(ctx, req.(*InfoEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InfoService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.grpc.InfoService/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).AddUser(ctx, req.(*InfoEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InfoService_UserDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).UserDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.grpc.InfoService/UserDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).UserDelete(ctx, req.(*InfoEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

// InfoService_ServiceDesc is the grpc.ServiceDesc for InfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.grpc.InfoService",
	HandlerType: (*InfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StrGame32",
			Handler:    _InfoService_StrGame32_Handler,
		},
		{
			MethodName: "StrGame64",
			Handler:    _InfoService_StrGame64_Handler,
		},
		{
			MethodName: "StrGame128",
			Handler:    _InfoService_StrGame128_Handler,
		},
		{
			MethodName: "AllUsers",
			Handler:    _InfoService_AllUsers_Handler,
		},
		{
			MethodName: "UserByID",
			Handler:    _InfoService_UserByID_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _InfoService_AddUser_Handler,
		},
		{
			MethodName: "UserDelete",
			Handler:    _InfoService_UserDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "infoservice.proto",
}
