// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpcProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	Game32(ctx context.Context, in *GameEmpty, opts ...grpc.CallOption) (*LogFight, error)
	Game64(ctx context.Context, in *GameEmpty, opts ...grpc.CallOption) (*LogFight, error)
	Game128(ctx context.Context, in *GameEmpty, opts ...grpc.CallOption) (*LogFight, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) Game32(ctx context.Context, in *GameEmpty, opts ...grpc.CallOption) (*LogFight, error) {
	out := new(LogFight)
	err := c.cc.Invoke(ctx, "/go.micro.srv.game.GameService/Game32", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) Game64(ctx context.Context, in *GameEmpty, opts ...grpc.CallOption) (*LogFight, error) {
	out := new(LogFight)
	err := c.cc.Invoke(ctx, "/go.micro.srv.game.GameService/Game64", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) Game128(ctx context.Context, in *GameEmpty, opts ...grpc.CallOption) (*LogFight, error) {
	out := new(LogFight)
	err := c.cc.Invoke(ctx, "/go.micro.srv.game.GameService/Game128", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility
type GameServiceServer interface {
	Game32(context.Context, *GameEmpty) (*LogFight, error)
	Game64(context.Context, *GameEmpty) (*LogFight, error)
	Game128(context.Context, *GameEmpty) (*LogFight, error)
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (UnimplementedGameServiceServer) Game32(context.Context, *GameEmpty) (*LogFight, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Game32 not implemented")
}
func (UnimplementedGameServiceServer) Game64(context.Context, *GameEmpty) (*LogFight, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Game64 not implemented")
}
func (UnimplementedGameServiceServer) Game128(context.Context, *GameEmpty) (*LogFight, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Game128 not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_Game32_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).Game32(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.game.GameService/Game32",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).Game32(ctx, req.(*GameEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_Game64_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).Game64(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.game.GameService/Game64",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).Game64(ctx, req.(*GameEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_Game128_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).Game128(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.game.GameService/Game128",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).Game128(ctx, req.(*GameEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.game.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Game32",
			Handler:    _GameService_Game32_Handler,
		},
		{
			MethodName: "Game64",
			Handler:    _GameService_Game64_Handler,
		},
		{
			MethodName: "Game128",
			Handler:    _GameService_Game128_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gameservice.proto",
}
